version: '3'

services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data-node1:/var/lib/cassandra/data

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    ports:
      - "9043:9042"
    volumes:
      - cassandra-data-node2:/var/lib/cassandra/data

volumes:
  cassandra-data-node1:
  cassandra-data-node2: